apiVersion: v1
kind: Service
metadata:
  labels:
    app: lab4-app
  name: lab4-app
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: lab4-app
  type: LoadBalancer
