apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: lab3-app
  labels:
    app: lab3-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab3-app
  template:
    metadata:
      labels:
        app: lab3-app
    spec:
      containers:
      - image: ifilyaninitmo/itdt-contained-frontend:master
        name: itdt-contained-frontend
        ports:
        - containerPort: 3000
          name: http
        envFrom: 
        - configMapRef:
            name: lab3-app-cm